# Generated by Django 5.1.3 on 2024-11-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Pasajeros', 'Pasajeros'), ('Carga', 'Carga'), ('Deportivo', 'Deportivo')], default='Pasajeros', max_length=50)),
            ],
            options={
                'permissions': [('can_edit_vehiculos', 'Puede agregar, visualizar, modificar vehículos (no puede eliminar)')],
            },
        ),
    ]
