# Generated by Django 5.1.3 on 2024-11-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_alter_vehiculo_create_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['-create_at'], 'permissions': [('can_edit_vehiculos', 'Puede agregar, visualizar, modificar vehículos (no puede eliminar)')]},
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
